machines:
  Genmitsu 3018-PROVer V2:
    simulator:
      min_x: 0
      max_x: 200
      min_y: 0
      max_y: 100
      figure_size: [10, 5]
    controller:
      baud_rate: 115200
      serial_port: "COM11"
      x_low_bound: 0
      x_high_bound: 200
      y_low_bound: 0
      y_high_bound: 100
      x_offset: 35
      y_offset: 25
